export const persons = [
  {
    id: 1,
    fullname: "Robert Angier",
    image: "/assets/images/persons/robert-angier.png",
    isOnline: true,
    isPrivate: true,
    password: "12345",
  },
  {
    id: 2,
    fullname: "Alfred Borden",
    image: "/assets/images/persons/alfred-borden.png",
    isOnline: true,
    isPrivate: true,
    password: "23456",
  },
  {
    id: 3,
    fullname: "Olivia Wenscombe",
    image: "/assets/images/persons/olivia-wenscombe.png",
    isOnline: false,
    isPrivate: false,
    password: "",
  },
  {
    id: 4,
    fullname: "Sarah Borden",
    image: "/assets/images/persons/sarah-borden.png",
    isOnline: true,
    isPrivate: false,
    password: "",
  },
];

export const messages = [
  {
    id: 1,
    user_id: 1,
    sender_id: 1,
    sender_message: "Sender 1. Message",
    user_message: null,
    created_at: "2023-12-19 14:49:57",
  },
  {
    id: 2,
    user_id: 1,
    sender_id: 1,
    sender_message: "Sender 2. Message",
    user_message: null,
    created_at: "2023-12-19 14:50:57",
  },
  {
    id: 3,
    user_id: 1,
    sender_id: 1,
    sender_message: null,
    user_message: "User 1. Message",
    created_at: "2023-12-19 14:52:57",
  },
  {
    id: 4,
    user_id: 1,
    sender_id: 1,
    sender_message: "Sender 3. Message",
    user_message: null,
    created_at: "2023-12-19 14:53:57",
  },
  {
    id: 5,
    user_id: 1,
    sender_id: 1,
    sender_message: "Sender 4. Message",
    user_message: null,
    created_at: "2023-12-19 14:55:57",
  },
  {
    id: 6,
    user_id: 1,
    sender_id: 1,
    sender_message: "Sender 5. Message",
    user_message: null,
    created_at: "2023-12-19 14:56:57",
  },
  {
    id: 7,
    user_id: 1,
    sender_id: 1,
    sender_message: null,
    user_message: "User 2. Message",
    created_at: "2023-12-19 14:58:57",
  },
  {
    id: 8,
    user_id: 1,
    sender_id: 1,
    sender_message: null,
    user_message: "User 3. Message",
    created_at: "2023-12-19 15:00:57",
  },
  {
    id: 9,
    user_id: 1,
    sender_id: 1,
    sender_message: "Sender 6. Message",
    user_message: null,
    created_at: "2023-12-19 15:05:57",
  },
  {
    id: 10,
    user_id: 1,
    sender_id: 2,
    sender_message: "Sender 1. Message",
    user_message: null,
    created_at: "2023-12-19 15:05:57",
  },
  {
    id: 11,
    user_id: 1,
    sender_id: 2,
    sender_message: null,
    user_message: "User 1. Message",
    created_at: "2023-12-19 18:25:57",
  },
  {
    id: 12,
    user_id: 1,
    sender_id: 2,
    sender_message: "Sender 2. Message",
    user_message: null,
    created_at: "2023-12-19 18:27:57",
  },
  {
    id: 13,
    user_id: 1,
    sender_id: 2,
    sender_message: "Sender 3. Message",
    user_message: null,
    created_at: "2023-12-19 18:30:57",
  },
  {
    id: 14,
    user_id: 1,
    sender_id: 3,
    sender_message: null,
    user_message: "User 1. Message",
    created_at: "2023-12-19 18:35:57",
  },
];
